# This file is the actual code for the Python runnable auto-documentation-generation
from dataiku.runnables import Runnable

from json import JSONDecodeError, dumps
import sys
import traceback

import pandas as pd
import dataiku
from dataikuapi.utils import DataikuException
import dataikuapi

print("LOADED!")

def is_project_empty(project_handle):
    """This traps the JSONDecodeError exception that occurs when generate_ai_description is called
    if the project has no datasets or recipes or flow zones"""

    # Check if there are any datasets
    has_datasets = len(project_handle.list_datasets()) > 0

    # Check if there are any recipes
    has_recipes = len(project_handle.list_recipes()) > 0

    return (not has_datasets) and (not has_recipes)


def get_dataset_long_description(dataset_handle):
    dataset_metadata = dataset_handle.get_metadata()
    try:
        return dataset_metadata['description']
    except KeyError:
        return ''


def get_dataset_short_description(dataset_handle):
    dataset_settings = dataset_handle.get_settings().get_raw()
    try:
        return dataset_settings['shortDesc']
    except KeyError:
        return ''


def get_dataset_column_descriptions(dataset_handle):
    dataset_schema = dataset_handle.get_schema()
    try:
        return [item["comment"] for item in dataset_schema['columns']]
    except KeyError:
        return ''


def dataset_has_full_documentation(project_handle, dataset_id):
    """
    Returns a boolean describing if a specific dataset meets ALL of the following requirements:
        1) It has a shortDesc that is not empty
        2) It has a description that is not empty
        3) ALL columns have descriptions that are not empty.

    Useful for determining if we should auto-generate a description to fill it in.
    """

    # project_handle = client.get_project(project_key)
    dataset_handle = project_handle.get_dataset(dataset_id)
    
    if not get_dataset_long_description(dataset_handle):
        # print(f'Dataset {dataset_id} lacks full documentation because empty: Long Description')
        return False
    
    if not get_dataset_short_description(dataset_handle):
        # print(f'Dataset {dataset_id} lacks full documentation because empty: Short Description')
        return False
    
    column_descriptions = get_dataset_column_descriptions(dataset_handle)

    if any(not s or not s.strip() for s in column_descriptions):
        # print(f'Dataset {dataset_id} lacks full documentation because empty: Column descriptions')
        return False
    
    # print(f'Dataset {dataset_id} has all description fields filled out.')
    return True


def is_project_description_empty(project_handle):
    """
    Returns a boolean describing if a specific project an existing description.
    Useful for determining if we should auto-generate a description to fill it in.
    """

    try:
        md = project_handle.get_metadata()
        if not md['description']:
            return True
    except KeyError:
        return True
    return False


def pretty_print_dict(d):
    import json
    print(json.dump(d, fp=sys.stdout, indent=4, sort_keys=True))


def flow_zone_has_description(flow_zone_handle):
    """
    Returns a boolean describing if a specific flow zone has an existing description.
    Useful for determining if we should auto-generate a description to fill it in.
    """
    try:
        # the auto-generated ones ONLY CREATE THE LONG DESCRIPTION, don't do the short one.
        flow_zone_settings                   = flow_zone_handle.get_settings().get_raw()
        flow_zone_description                = flow_zone_settings.get('description', '')
        flow_zone_description_length         = len(flow_zone_description)

        # can't use the "not " version, must use len>0 for some reason.
        flow_zone_has_a_nonempty_description = len(flow_zone_description) > 0 

        return flow_zone_has_a_nonempty_description
    except JSONDecodeError:
        print(f"[ERROR] Trying to get description for {flow_zone_settings['name']}")
        pretty_print_dict(flow_zone_settings)
        return False
    
    
def is_flowzone_empty(flowzone_handle):
    """This traps the JSONDecodeError exception that occurs when generate_ai_description is called
    if the flowzone has no datasets or recipes
    
      There has to be at least one recipe or one dataset in order to explain a zone.

    """
    for i in flowzone_handle.items:
        if type(i) in [dataiku.Dataset, dataikuapi.dss.recipe.DSSRecipe, dataikuapi.dss.dataset.DSSDataset]:
            return False
    return True


def read_first_dataset_row(project_key, dataset_name):
    """Returns a boolean if the first row of the dataset was readable.
    False implies the dataset was either empty or an exception occurred.
    Useful for determining if autogenerated descriptions of a dataset are possible.
    """
    try:
        dataset_handle = dataiku.Dataset(dataset_name, project_key=project_key)
        df = dataset_handle.get_dataframe(limit=1)

        # Check if the dataframe is empty (no rows)
        if df.empty:
            print("Dataset is empty.")
            return False

        return True

    except Exception as e:
        # Catch any exception that might occur
        return False




class MyRunnable(Runnable):
    """The base interface for a Python runnable"""

    def __init__(self, project_key, config, plugin_config):
        """
        :param project_key: the project in which the runnable executes
        :param config: the dict of the configuration of the object
        :param plugin_config: contains the plugin settings
        """
        self.project_key = project_key
        self.config = config
        self.plugin_config = plugin_config
        
        self.num_AI_services_used = 0
        self.LANGUAGE         = self.config['language']
        self.PROJECT_PURPOSE  = self.config['project_purpose']
        self.PROJECT_LENGTH   = self.config['project_length']
        self.SAVE_DESCRIPTION = self.config['save_description']

        self.client = dataiku.api_client()
        
    def get_AI_services_used_count(self):
        return self.num_AI_services_used
        
    def get_progress_target(self):
        """
        If the runnable will return some progress info, have this function return a tuple of 
        (target, unit) where unit is one of: SIZE, FILES, RECORDS, NONE
        """
        return None
    
    def run_projects(self):
        """
        x
        """
        
        PROJECTS_LIST    = self.client.list_project_keys()
        
        # iterate through the list of projects
        for project_key in PROJECTS_LIST:
            try:
                project_handle = self.client.get_project(project_key)

                # Ensure that the project meets the requirements for creating AI generated descriptions
                if is_project_empty(project_handle):
                    print(f"[SKIP] Project must have datasets or recipes in flow, can't create description: {project_key}")
                    continue

                # Only generate descriptions if there is not one already:
                if is_project_description_empty(project_handle):
                    print(f"Project {project_key} has an empty description, generating AI description for it.")
                    self.num_AI_services_used += 1

                    # https://developer.dataiku.com/latest/api-reference/python/projects.html#dataikuapi.dss.project.DSSProject.generate_ai_description
                    project_handle.generate_ai_description(
                        language=self.LANGUAGE,
                        purpose=self.PROJECT_PURPOSE,
                        length=self.PROJECT_LENGTH,
                        save_description=self.SAVE_DESCRIPTION
                    )

            except JSONDecodeError:
                print(f"[JSONDecodeError] Creating project description for {project_key}")
                continue

    def run(self, progress_callback):
        """
        Do stuff here. Can return a string or raise an exception.
        The progress_callback is a function expecting 1 value: current progress
        """
        # raise Exception("unimplemented")
        # client = dataiku.api_client()
        self.run_projects()
        return None